name = "chat_server"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
mist = ">= 4.0.6 and < 5.0.0"
gleam_http = ">= 3.7.2 and < 4.0.0"
gleam_otp = ">= 0.16.1 and < 1.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"
decode = ">= 1.1.0 and < 2.0.0"
youid = ">= 1.2.0 and < 2.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"
bath = ">= 2.0.0 and < 3.0.0"
mungo = ">= 0.27.0 and < 1.0.0"
dot_env = ">= 1.2.0 and < 2.0.0"
bison = ">= 1.7.0 and < 2.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
nessie_cluster = ">= 0.3.0 and < 1.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
erlang_unstable = {path = "../erlang_unstable"}
nessie = {path = "../nessie"}

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
stratus = ">= 0.9.5 and < 1.0.0"
